[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/uploads/*"
  to = "https://nodejs207.dszcbaross.edu.hu/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/users/*"
  to = "https://nodejs207.dszcbaross.edu.hu/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/animals/*"
  to = "https://nodejs207.dszcbaross.edu.hu/animals/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/cities/*"
  to = "https://nodejs207.dszcbaross.edu.hu/cities/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/messages/*"
  to = "https://nodejs207.dszcbaross.edu.hu/messages/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "https://nodejs207.dszcbaross.edu.hu/socket.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200